### ISSUE TITLE
TypeError: Illegal constructor

### ISSUE THREAD

**Issue by aldarund** [angular-ui/ui-mask#168]
```
TypeError: Illegal constructor
  at triggerChangeEvent(~/angular-ui-mask/dist/mask.js:489:0)
  at HTMLInputElement.blurHandler(~/angular-ui-mask/dist/mask.js:477:0)
  at HTMLInputElement.jQuery.event.dispatch(~/jquery/dist/jquery.js:5087:0)
  at HTMLInputElement.elemData.handle(~/jquery/dist/jquery.js:4895:0)
  at HTMLInputElement.wrapped(~/raven-js/src/raven.js:265:0)
```
Happens on this line https://github.com/angular-ui/ui-mask/blob/master/src/mask.js#L479 on mobile devices with android 4.*  ( maybe other too, not sure)

**Comment by lukepfeiffer10** [comment]
Hmmm that is odd but it looks like you are running into this kind of an [issue](http://stackoverflow.com/questions/18814683/what-is-rect-function-in-chrome-firefox-for).

Thanks for pointing this out.

**Comment by aldarund** [comment]
Im just collecting a js errors into sentry using raven.js and noticed this error to be happening on android 4.x with android build in browser, dont seem to be  happen for anyone else, at least in my userbase

**Comment by lukepfeiffer10** [comment]
1.8.7 should have the fix for this if you want to try it out. I was unable to recreate the issue myself.
